packages:
  - packages/**
  - apps/*

catalog:
  '@ant-design/icons-vue': ^7.0.1
  '@commitlint/cli': ^19.8.1
  '@commitlint/config-conventional': ^19.8.1
  '@primeuix/utils': ^0.6.1
  '@primevue/icons': ^4.3.9
  '@tailwindcss/vite': ^4.1.12
  '@types/eslint': ^9.6.1
  '@types/lodash-es': ^4.17.12
  '@types/postcss-pxtorem': 6.0.1
  '@types/uuid': ^10.0.0
  '@typescript-eslint/eslint-plugin': ^8.42.0
  '@typescript-eslint/parser': ^8.42.0
  '@vitejs/plugin-basic-ssl': ^2.1.0
  '@vitejs/plugin-vue': ^6.0.1
  '@vitejs/plugin-vue-jsx': ^5.1.1
  '@vueuse/core': ^13.9.0
  animejs: ^4.2.2
  axios: ^1.11.0
  dayjs: ^1.11.18
  eslint: ^9.34.0
  eslint-config-standard-with-typescript: ^42.0.1
  eslint-plugin-vue: ^10.4.0
  less: ^4.4.1
  localforage: ^1.10.0
  lodash-es: ^4.17.21
  lottie-web: ^5.13.0
  postcss: ^8.5.6
  postcss-pxtorem: ^6.1.0
  primevue: ^4.3.9
  tailwind-merge: ^3.3.1
  tailwindcss: ^4.1.12
  tailwindcss-primeui: ^0.6.1
  typescript: ^5.9.2
  uuid: 11.1.0
  vite: ^7.1.4
  vite-plugin-eslint: ^1.8.1
  vite-plugin-mkcert: ^1.17.8
  vite-plugin-svg-icons: ^2.0.1
  vue: 3.5.21
  vue-i18n: ^11.1.11
  vue-router: 4.5.1
  vue-tsc: ^3.0.6
  marked: ^17.0.0
